version: '2.2'
services:
    api:
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - 8000:80
        volumes:
            - ./public/api:/var/www/html
